### ISSUE TITLE
Implement `TextEditor`

### ISSUE THREAD

**Issue by MaxDesiatov** [TokamakUI/Tokamak#173]
This is probably going to be one of the most complex views, but definitely worth it and is something that I see that people are requesting.

**Comment by mcritz** [comment]
+1 for this. TextEditor (in SwiftUI 2020) is nearly one-for-one with <textarea>

**Comment by mcritz** [comment]
Thank you very much!

**Comment by MaxDesiatov** [comment]
Thanks for helping us prioritize this! 🙂
