### ISSUE TITLE
HTML + Binding 

### ISSUE THREAD

**Issue by vi4m** [TokamakUI/Tokamak#278]
I've tried to build `HTML` which will react to external events from external components(such as Button click), through "Binding" wrapper.

<img width="633" alt="struct SVGCircle View 7" src="https://user-images.githubusercontent.com/552398/93870129-0922eb00-fccd-11ea-9f10-f6571f6b07c4.png">

It does render with intial value, but it doesn't re-render after sending new value. 

Questions: 
* How to properly handle this?
* It this a bug? 
* Should I use DynamicHTML instead?

**Comment by MaxDesiatov** [comment]
Hi @vi4m, thanks for reporting this, it looks like a bug to me. I'm investigating it now.

**Comment by MaxDesiatov** [comment]
This is fixed in the `main` branch now and will be included in the next release of Tokamak. Thanks again for catching the issue!

**Comment by vi4m** [comment]
Thanks for a quick fix! working as expected now 👍

**Comment by MaxDesiatov** [comment]
That's great! Feel free to reopen or to create new issue if you have any problems/questions 🙂
