### ISSUE TITLE
0.4.0 upgrade / regression?

### ISSUE THREAD

**Issue by vi4m** [TokamakUI/Tokamak#283]
After upgrading to 0.4.0, everything builds fine(after minor JavascriptKit API changes), but after opening the page with Google Chrome i got this:

![image](https://user-images.githubusercontent.com/552398/94911559-9f61c880-04a6-11eb-9811-a80cc478fb90.png)

I've tried to re-create project with `carton init --template tokamak` and an error still exists.

Any ideas how to migrate?

**Comment by MaxDesiatov** [comment]
Hi @vi4m, thanks for reporting this. What version of `carton` do you use? You can check that by running `carton --version. Please make sure you have version 0.6.0 or greater, as this new version of `carton` ships with the new JavaScriptKit runtime required by Tokamak 0.4.0. You can upgrade `carton` with `brew upgrade`. Does that resolve your issue?

**Comment by MaxDesiatov** [comment]
BTW, for `carton init --template tokamak` to work you need `carton` 0.6.1`, but that will be installed anyway if you run `brew upgrade`.

**Comment by vi4m** [comment]
Thanks! It worked! 
I guess, I jumped on new release too quickly, without reading relase notes, sorry!

**Comment by MaxDesiatov** [comment]
No problem at all, happy to help 🙂
