### ISSUE TITLE
Colors should change depending on light/dark color scheme

### ISSUE THREAD

**Issue by MaxDesiatov** [TokamakUI/Tokamak#290]
Thanks to the amazing research done by @Cosmo, it can be seen that multiple colors change based on the current color scheme, not just `primary`/`secondary`:

![image](https://user-images.githubusercontent.com/112310/96373932-79efe280-1167-11eb-99cc-5f5e61bcb6d0.png)

**Comment by MaxDesiatov** [comment]
As Devran mentioned, we should pay attention to the `var provider: AnyColorBox` property on `Color`.

**Comment by Cosmo** [comment]
In my research, for OpenSwiftUI, I found out that the type `Color` doesn't hold any color values -- only another class type of `AnyColorBox`.
Its the renderes job to figure out what that value of `AnyColorBox` represents.

By default, in SwiftUI you have `SystemColorType: AnyColorBox` and `DisplayP3: AnyColorBox`.
`SystemColorType` represents values like `.red`, `.blue`, `.purple`, -- so only names.
And `DisplayP3` stores values in RGBA channels.

A color of type `DisplayP3` is always the same color -- whereas `.red` of `SystemColorType` can be different depending on the environment (for instance color scheme).

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/6125/96375200-c93e0f00-1177-11eb-8ef1-e6446ea2710c.png">

This architecutre gives the possiblity to implement `HexColor: AnyColorBox` if you want to.
Or go even crazier. You could write `Nanometer: AnyColorBox` and store the color value in nanometers and draw with UV or infrared light -- all without modifying a thing in `Color`.

You can find my implementation of `Color` here: 
https://github.com/Cosmo/OpenSwiftUI/blob/master/Sources/OpenSwiftUI/Views/Color.swift

A similar thing is going on with the `Font` type where font sizes are not stored in the Core implementation. Only the renderer knows how big a `.title` should be and look like. This architecture is a bit more complex, but its the only way to become compatible with Apple's SwiftUI and remove platform specific dependencies to get fully platform-agnostic.

**Comment by carson-katri** [comment]
`Image` is also a ["late-binding token"](https://www.google.com/search?q=%22late+binding+token%22+site:developer.apple.com), I assume for SFSymbols and the `imageScale`/other image-specific environment values.
