### ISSUE TITLE
Can't build Tokamak project - carton dev command

### ISSUE THREAD

**Issue by nikitamounier** [TokamakUI/Tokamak#296]
After I make a new Tokamak project using the `carton init --template tokamak` command, I can't build it with the `carton dev` command (in Terminal and the integrated VSCode console). Instead, I get this error:

`Error: Process failed with non-zero exit status and following error output:
error: terminated(72): OLDPWD=/Users/benoitmounier __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x2 TERM_SESSION_ID=413A1A5C-DD4D-4D38-9CE8-343D6B4A59E6 PWD=/Users/benoitmounier/WebSwiftUI SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.z5lhB5EgTe/Listeners SHELL=/bin/zsh _=/usr/local/bin/carton TERM_PROGRAM=Apple_Terminal TERM=xterm-256color XPC_SERVICE_NAME=0 PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin XPC_FLAGS=0x0 HOME=/Users/benoitmounier USER=benoitmounier SHLVL=1 TMPDIR=/var/folders/r7/vq4ycw_571lf8n09c5jhbkc40000gn/T/ LANG=en_GB.UTF-8 LOGNAME=benoitmounier TERM_PROGRAM_VERSION=433 /usr/bin/xcrun --sdk macosx --find xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH`

This error seems to be related to `XCTest` in the `Test` folder automatically generated by the Tokamak template. However, I get the same error even when I delete it.

**Comment by MaxDesiatov** [comment]
Hi @nikitamounier, thanks for reporting this. Do you have Xcode 11.4 or later installed? If so, what happens when you run `xcrun --sdk macosx --find xctest` in terminal?

**Comment by nikitamounier** [comment]
Hi @MaxDesiatov , I'm on Xcode 12.1. When I run that command in terminal I get:
`xcrun: error: unable to find utility "xctest", not a developer tool or in PATH`
I'm not enrolled in the Apple Developer Program, could that be the root of the issue?

**Comment by MaxDesiatov** [comment]
I don't think that the developer program enrolment could be related. Does this SO answer resolve the issue for you? https://stackoverflow.com/questions/61501298/xcrun-error-unable-to-find-utility-xctest-not-a-developer-tool-or-in-path

**Comment by nikitamounier** [comment]
Yes, the SO answer works! Thanks a lot!
