### ISSUE TITLE
TokamakDemo build failed

### ISSUE THREAD

**Issue by RayZhao1998** [TokamakUI/Tokamak#305]
The fail message:  'buildLimitedAvailability' is only available in macOS 11.0 or newer.

Environment: macOS Big Sur 11.0.1 (20B29)

<img width="909" alt="截屏2020-11-26 上午1 10 53" src="https://user-images.githubusercontent.com/22616933/100260494-6a449480-2f84-11eb-8713-5458234d597f.png">

**Comment by RayZhao1998** [comment]
One more question, if I want to contribute to Tokamak, how to debug it?

**Comment by MaxDesiatov** [comment]
@RayZhao1998 sorry for the delay, this is resolved in #329.
