### ISSUE TITLE
What is the difference between HTML and DynamicHTML?

### ISSUE THREAD

**Issue by revolter** [TokamakUI/Tokamak#388]
I'm sorry if this is not the best place to ask questions, but I couldn't find any official documentation except the README file.

What are the differences between `HTML` and `DynamicHTML`, and how do I know when I need to use one over the other?

**Comment by MaxDesiatov** [comment]
`DynamicHTML` is provided by the `TokamakDOM` module and has a `listeners` property with a corresponding initializer parameter. You can pass closures that can handle `onclick`, `onmouseover` and other DOM events for you ([check out MDN docs for the full list](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers)). `HTML` doesn't support event listeners, and is declared in the `TokamakStaticHTML` module, which `TokamakDOM` re-exports. The benefit of `HTML` is that you can use it for static rendering in libraries like [TokamakVapor](https://github.com/TokamakUI/TokamakVapor) and [TokamakPublish](https://github.com/TokamakUI/TokamakPublish). Does that answer your question?

**Comment by revolter** [comment]
Yes, thank you! Maybe this answer could be added in the code documentation or somewhere on GitHub.

**Comment by MaxDesiatov** [comment]
Great point, I'm on it 👍
