### ISSUE TITLE
@ObservedObject is a get-only property

### ISSUE THREAD

**Issue by kuglee** [TokamakUI/Tokamak#392]
**Describe the bug**
```
   ERROR   cannot assign to property: 'testObservable' is a get-only property
  19 |      self.testObservable = TestObservable()
     |           ^
```

**To Reproduce**
```swift
import TokamakShim

struct TokamakApp: App {
    var body: some Scene {
        WindowGroup("Tokamak App") {
            ContentView()
        }
    }
}

public class TestObservable: ObservableObject {
  @Published var test = 0
}

public struct ContentView: View {
  @ObservedObject var testObservable: TestObservable
  
  public init() {
    self.testObservable = TestObservable()
  }

  public var body: some View {
    EmptyView()
  }
}

// @main attribute is not supported in SwiftPM apps.
// See https://bugs.swift.org/browse/SR-12683 for more details.
TokamakApp.main()
```

**Expected behavior**
The code compiles successfully.

**Desktop (please complete the following information):**
 - OS: **macOS**
 - Browser: **Safari**
 - Version of the browser: **14.0.3 (16610.4.3.1.4)**
 - Version of Tokamak: **0.6.1**

**Comment by foscomputerservices** [comment]
Did you try `self._testObservable = TestObservable()`?  It is my understanding that this is how Swift actually stores property wrappers ([reference](https://docs.swift.org/swift-book/LanguageGuide/Properties.html)).

**Comment by kuglee** [comment]
Then I get a different error:
```bash
   ERROR   cannot assign value of type 'TestObservable' to type 'ObservedObject<TestObservable>'
  20 |      self._testObservable = TestObservable()
     |
```

**Comment by foscomputerservices** [comment]
I apologize, I should not have replied from memory.  I too have encountered this issue as a difference between the way that iOS works.  The following workaround will work:

`self._testObservable = ObservedObject(wrappedValue: TestObservable())`

**Comment by kuglee** [comment]
Awesome. Thanks!
