### ISSUE TITLE
Content with spacer jumps when blurring and focusing the page 

### ISSUE THREAD

**Issue by revolter** [TokamakUI/Tokamak#395]
**Describe the bug**

When using a combination of `ZStack`, `VStack` and `Spacer`, some views jump when changing to another tab and back again.

**To Reproduce**
1. Download the attached project
2. Run `carton dev`
3. Open the webpage
4. Select another tab
5. Select the initial tab

**Expected behavior**

The text should remain outside the rectangle.

**Screenshots**
If this is a layout/rendering issue, please provide screenshots for both Tokamak and SwiftUI that highlight the difference.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.3 (20D91)
 - Browser: Safari
 - Version of the browser: 14.0.3 (16610.4.3.1.7)
 - Version of Tokamak: 0.6.1

**Smartphone (please complete the following information):**
 - Version of the browser [e.g. 22]
 - Version of Tokamak [e.g. 0.6.1]

**Additional context**

[1616847509.zip](https://github.com/TokamakUI/Tokamak/files/6215857/1616847509.zip)

**Comment by MaxDesiatov** [comment]
Thanks for the detailed report and sorry for the delayed reply! I assume that we can fix this by our layout code rewrite in https://github.com/TokamakUI/Tokamak/pull/379, but there may be an easier fix. Unfortunately, I don't have an estimate for when I'll be able to investigate this in a detailed way. In the meantime, I'm happy to review PRs that fix this.
