### ISSUE TITLE
Adding padding to a view contained in a Button causes the Button to disappear

### ISSUE THREAD

**Issue by foscomputerservices** [TokamakUI/Tokamak#403]
When adding padding to the content of a ```Button```, the ```<button>``` is no longer rendered in the HTML.

```swift
struct ContentView: View {
    var body: some View {
        Button {
        } label: {
            Text("Button")
                .padding()
        }
    }
}
```

Removing the ```.padding()``` restores the button in the output.

**Screenshots**
(I could provide a screenshot, but just envision a blank screen, we'll save a few bytes on GitHub 😁)

This is using the latest code on the *main* branch.

**Comment by MaxDesiatov** [comment]
Closing this as resolved in #409.
