### ISSUE TITLE
Can't find CGSize or CGFloat type

### ISSUE THREAD

**Issue by softknife** [TokamakUI/Tokamak#450]
**Describe the bug**
I found CGXX type error when i try to build a swift web app

**Screenshots**
this is my code
```swift
struct CalculatorButton: View {
    
    var fontSize : CGFloat = 38
    let title : String
    var size:CGSize
    let backgroundColor:Color
    let action:()->Void
    var body: some View {
        Button(action: action) {
            Text(title)
                .font(.system(size: fontSize))
                .foregroundColor(.white)
                .frame(width: size.width, height: size.height, alignment: .center)
                .background(backgroundColor)
                .cornerRadius(size.width * 0.5)
        }
    }
}

```
This is error info :
[Error info](https://github.com/swift-joking/TokamakLearning/blob/main/Bugs/CGxx%20type%20error%20-%202021-10-01%202.08.12.png)

***Desktop ***
 - OS: [11.5.2 macOS]
 - Browser :chrome
 - Version of the browser : 94.0.4606.61
 - Version of Tokamak 0.8.0

**Comment by MaxDesiatov** [comment]
@softknife thanks for the report! Would you be able tor provide the full error message here? Seems like the most important part of it is cut off on the screenshot

**Comment by MaxDesiatov** [comment]
If the error you're getting is about unavailable `CGFloat`, you'll have to add `import Foundation` in your source file to get access to this type, since it's defined in Foundation, not Tokamak.

**Comment by softknife** [comment]
ok , done , thank you @MaxDesiatov
