### ISSUE TITLE
Hacktoberfest?

### ISSUE THREAD

**Issue by agg23** [TokamakUI/Tokamak#451]
Not sure if it's something the maintainers are up to, but you should consider participating in [Hacktoberfest](https://hacktoberfest.digitalocean.com/). The only direct action it requires on your part is adding the `Hacktoberfest` tag to the project, and it hopefully will drive more people to contribute to the project in a meaningful way by aiding in its discoverability.

**Comment by MaxDesiatov** [comment]
This is something we could consider, although I'm wary of spammy PRs. Would you be able to link to the participation rules for repositories? I'm not able to find any information for how repositories can participate, only rules for would-be contributors.

**Comment by agg23** [comment]
Take a look at the [resources](https://hacktoberfest.digitalocean.com/resources) and [FAQ](https://hacktoberfest.digitalocean.com/faq) sections; they both mention some stuff about handling spam/ensuring quality contributions. There have been problems with spam in the past, but I think it's been more of extremely trivial PRs rather than actual garbage.

**Comment by MaxDesiatov** [comment]
Thanks, I've added the repository to the topic and added labels to a few issues. Also created a simple `CONTRIBUTING.md`. Let's how it goes 👍
