### ISSUE TITLE
TextField Not Rendering the field

### ISSUE THREAD

**Issue by justbane** [TokamakUI/Tokamak#455]
**Describe the bug**
TextField doesn't draw a field on the page. It only adds the placeholder text as text in a span

**To Reproduce**
1. add a TextField to the body View

`struct ContentView: View {
    @State var fullName: String = ""
    
    var body: some View {
        VStack {
            Text("Swift WASM App")
                .font(.title)
            HStack {
                Text("Hello there, \(fullName)!")
            }
            .padding()
            
            TextField("Full Name", text: $fullName)
            Button(action: {
                fullName = "John Doe"
            }) {
                Text("Add name")
            }
            
        }
        .padding()
    }
}`

**Expected behavior**
I would hope for a TextField to show in the page

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Safari 15
 - Version of the browser [15]
 - Version of Tokamak [e.g. 0.8.0]

**Additional context**
Is there any additional documentation?

**Comment by carson-katri** [comment]
Would you be able to try this on the `main` branch, I think it may be resolved.

**Comment by justbane** [comment]
Yup - verified works in main branch.

Any timing on the next release? I don't mind working on master but would rather not be on the bleeding edge :)

**Comment by MaxDesiatov** [comment]
We're preparing SwiftWasm 5.5 for release and I'd like to tag new release of Tokamak with a few basic `async` helpers. I don't have a specific timeline for this, but if all goes well it should be weeks from now rather than months.
