### ISSUE TITLE
error: no type named 'Sendable' in module 'Swift'

### ISSUE THREAD

**Issue by justbane** [TokamakUI/Tokamak#456]
**Describe the bug**
Just came back to my project after a bit and tried to run it. I receive a Package manifest parse error.

`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/Combine.framework/Modules/Combine.swiftmodule/x86_64-apple-macos.swiftinterface:2599:50: error: no type named 'Sendable' in module 'Swift'
extension Combine.Subscribers.Completion : Swift.Sendable {}`

I get this error multiple times in the terminal window.

**To Reproduce**
Just run carton dev

**Expected behavior**
Would start the dev server and launch the browser.

**Screenshots**
If this is a layout/rendering issue, please provide screenshots for both Tokamak and SwiftUI that highlight the difference.

**Desktop (please complete the following information):**
 - OS: [macOS 11.6]
 - Version of Tokamak [main]

**Additional context**

**Comment by MaxDesiatov** [comment]
@justbane do you have Xcode 13 installed? If so, this version is currently not supported. A workaround is to switch to an earlier version of Xcode, ideally Xcode 12.5.1

**Comment by carson-katri** [comment]
I _think_ it works with 13.0, just not 13.1 (which has the Monterey SDK), but I could be mistaken.

**Comment by justbane** [comment]
Yup - I am sitting on 13.1

**Comment by MaxDesiatov** [comment]
@carson-katri thanks I've added a note that Xcode 13.1 is not supported in https://github.com/TokamakUI/Tokamak/commit/a5a05b4826057983b6abc605749e0eeb461300c6

**Comment by CharlesMariaWX** [comment]
Is there any plan on Xcode 13.1 becoming supported? My only development device is one of the new M1X MBPs.

**Comment by MaxDesiatov** [comment]
It should work with SwiftWasm 5.5, which I'm going to formally announce later today. You can already start using it, just update your `carton` installation with Homebrew.

Does that resolve the issue for you?

**Comment by MaxDesiatov** [comment]
Closing as fixed in SwiftWasm 5.5, feel free to reopen if you're still seeing this with that version.
