### ISSUE TITLE
Use Dynamic Content in Statically Hosted Websites

### ISSUE THREAD

**Issue by BastianKusserow** [TokamakUI/Tokamak#494]
Hey there,
I was playing around with Tokamak and as I was doing so, I wondered if there is a possibility yet to use `TokamakStaticHTML` (for instance via the TokamakPublish library) for a fast first render of the website, but then use some dynamic content like e.g. buttons that can react to user interactions and can execute code via WebAssembly to modify the page.
If so, could someone point me to a example on how to accomplish that? :)

**Comment by MaxDesiatov** [comment]
Hi!

This is a great idea, but unfortunately I'm not aware of existing implementations.

What you've described looks quite close to what I had in mind when creating https://github.com/TokamakUI/Tokamak/issues/257. Let me know if you think as well, then maybe we should close one of the issues as a duplicate.

**Comment by BastianKusserow** [comment]
Hi Max, thanks for the quick reply!
The issue you mentioned sounds exactly like what I wanted to do, sorry for the duplicate. I'll close the issue as duplicate.
