### ISSUE TITLE
How to handle CORS?

### ISSUE THREAD

**Issue by ayrtonsoftware** [TokamakUI/Tokamak#524]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If this is a layout/rendering issue, please provide screenshots for both Tokamak and SwiftUI that highlight the difference.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 12.4]
 - Version of the browser [e.g. 22]
 - Version of Tokamak [e.g. 0.10.1]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS15.1]
 - Version of the browser [e.g. 22]
 - Version of Tokamak [e.g. 0.10.1]

**Additional context**

**Comment by carson-katri** [comment]
Can you describe what you are trying to do? I think CORS should be handled by your server, not the frontend framework.

**Comment by ayrtonsoftware** [comment]
I am trying to use JDoodle plugin. I either get a 400 error from the site or a CORS error.

`struct CompilerView: View {
  init() {
    let document = JSObject.global.document
    let script = document.createElement("script")
    script.setAttribute("src", "https://www.jdoodle.com/assets/jdoodle-pym.min.js")
    script.setAttribute("type", "text/javascript")
    document.head.appendChild(script)
  }
  var body: some View {
      VStack {         
        DynamicHTML("a", ["href": "https://www.google.com"]) {
          Text("This is a link")
        }
      HTML("script", ["src": "https://www.jdoodle.com/assets/jdoodle-pym.min.js", "type": "text/javascript"]) 
      HTML("div", [
        "data-pym-src": "https://www.jdoodle.com/plugin",
        "data-language": "java",
        "data-version-index": "4",
        "data-libs":"mavenlib1, mavenlib2",
        "Access-Control-Allow-Origin": "*"
      ])
    }
  }
}`

**Comment by ayrtonsoftware** [comment]
It appears to be an Apple Safari issue as it works in Chrome... I should have known.....
